#ifndef _CONFIGURATION_H
#define _CONFIGURATION_H

#define MAX_BODY_SIZE 2024

#define MAX_HEADER_ENTRIES 25
#define MAX_HEADER_KEY_LENGTH 64
#define MAX_HEADER_VALUE_LENGTH 512

// Response
#define RESPONSE_DEFAULT_STATUS_CODE 500
#define MAX_RESPONSE_BODY_SIZE 2048

// Routing
#define HTTP_ROUTER_MAX_ROUTES 10
#define HTTP_ROUTER_ROUTE_BUFFER 256

#define HTTP_ROUTE_MAX_PARTS 5
#define HTTP_ROUTE_MAX_PART_SIZE 65

// HTTP-methods
#define HTTP_METHOD_UNKNOWN 0
#define HTTP_METHOD_GET 1
#define HTTP_METHOD_POST 2
#define HTTP_METHOD_DELETE 3
#define HTTP_METHOD_PUT 4
#define HTTP_METHOD_PATCH 5
#define HTTP_METHOD_OPTIONS 6

// Board
#define BOARD_ESP_8266 1
#define BOARD_ESP_32 2
#define BOARD BOARD_ESP_8266

#define __DEV__

#endif
